name: Discord_Luckperms
version: '${version}'
main: plugin.filled_sky24811.info.discord_luckperms.Discord_Luckperms
api-version: '1.20'
default-permission: op
depend: [LuckPerms]
commands:
  dl_link:
    description: '[AdminOnly]Discord-Minecraft'
    permission: Discord_Luckperms.dl_link
  discord_luckperms:
    description: '[AdminOnly]AdminCommands'
    permission: Discord_Luckperms.discord_luckperms